run:
  timeout: 5m
  modules-download-mode: vendor
  skip-dirs:
    - store/storetest/mocks
    - vendor
    - viper
    - i18n

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: false

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - golint
    - gosimple
    - govet
    - ineffassign
    - scopelint
    - structcheck
    - unconvert
    - unused
    - varcheck
    # TODO: enable this later
    # - errcheck

issues:
  exclude-rules:
    - linters:
        # ignore unused warnings from enterprise code
        # add more as required.
        - unused
      text: "RedisSupplier|LocalCacheSupplier|Enterprise"

    - linters:
        - scopelint
      # ignore warnings from table tests. https://github.com/kyoh86/scopelint/issues/4
      path: ".*_test.go|store/storetest"

    - linters:
        - golint
      path: "api|app|cmd|mlog|model|testlib|services|store|utils|web|"
